### ISSUE TITLE
Drafting UI for first webpage

### ISSUE THREAD

**Issue by ddhuy77** [nguyencaominhduc/SEPM#10]

**Comment by ddhuy77** [comment]
[DraftUI-leftsidebarfullgrid.zip](https://github.com/nguyencaominhduc/SEPM/files/4532422/DraftUI-leftsidebarfullgrid.zip)

A draft UI of the first page of our web app, more debugging sessions needed to make it functional. Have a review with this draft by downloading the above project zip file.

**Comment by ddhuy77** [comment]
Updated draft UI (Both homepage and review page included). Some scripts are still unable to be executed.

[DraftUI-leftsidebarfullgrid-v1.2.zip](https://github.com/nguyencaominhduc/SEPM/files/4534853/DraftUI-leftsidebarfullgrid-v1.2.zip)

**Comment by nguyencaominhduc** [comment]
[Front-end-v1.3.zip](https://github.com/nguyencaominhduc/SEPM/files/4540095/Front-end-v1.3.zip)

Updated draft UI. Fixing scripts are unable to execute. Redesign UI level

**Comment by nguyencaominhduc** [comment]
[Front-end-v1.31 (2).zip](https://github.com/nguyencaominhduc/SEPM/files/4546223/Front-end-v1.31.2.zip)
