### ISSUE TITLE
Collect data

### ISSUE THREAD

**Issue by pham-hang** [nguyencaominhduc/SEPM#7]

**Comment by nguyencaominhduc** [comment]
[Tiki_Data.xlsx](https://github.com/nguyencaominhduc/SEPM/files/4472965/Tiki_Data.xlsx)
[Shopee_Data.xlsx](https://github.com/nguyencaominhduc/SEPM/files/4472966/Shopee_Data.xlsx)
[Lazada 2 Data.xlsx](https://github.com/nguyencaominhduc/SEPM/files/4472967/Lazada.2.Data.xlsx)

API:
https://open.shopee.com/documents?module=63&type=2&id=52

https://open.lazada.com/doc/doc.htm?spm=a2o9m.11193487.0.0.3ac413feQs4X1L#?nodeId=11207&docId=108479

https://open.tiki.vn/#update-product-information

https://developers.google.com/shopping-content/v2/quickstart

**Comment by nguyencaominhduc** [comment]
[Tiki_Laptop_MinhDuc.xlsx](https://github.com/nguyencaominhduc/SEPM/files/4493284/Tiki_Laptop_MinhDuc.xlsx)
[Lazada_Laptop_MinhDuc.xlsx](https://github.com/nguyencaominhduc/SEPM/files/4493285/Lazada_Laptop_MinhDuc.xlsx)
[Shopee_Laptop_MinhDuc.xlsx](https://github.com/nguyencaominhduc/SEPM/files/4493286/Shopee_Laptop_MinhDuc.xlsx)

**Comment by ddhuy77** [comment]
[VGA_Data_Collection_Huy.zip](https://github.com/nguyencaominhduc/SEPM/files/4493838/VGA_Data_Collection_Huy.zip)
